import { redis } from '../../shared/utils/redis.js'
import { prisma } from '../../shared/utils/prisma.js'
import { getAccessToken, refreshSpotifyToken } from '../auth/platform.service.js'
import { resolveBlueprint } from '../resolver/index.js'
import {
  getSpotifyUserId,
  createSpotifyPlaylist,
  addTracksToSpotifyPlaylist,
  getSpotifyAudioFeatures,
} from './platforms/spotify.js'
import { harmonicSequence } from './harmonic-sequencer.js'
import type { PlaylistBlueprint, ResolvedTrack } from '../../shared/types/index.js'

const BLUEPRINT_KEY = (id: string) => `blueprint:${id}`

export interface ExportResult {
  platformPlaylistId: string
  platformPlaylistUrl: string
  trackCount: number
  failedTracks: number
}

export async function exportBlueprint(
  blueprintId: string,
  platform: string,
  userId: string,
): Promise<ExportResult> {
  // Load blueprint (§5.7 — preserved in Redis for exactly this reason)
  const raw = await redis.get(BLUEPRINT_KEY(blueprintId))
  if (!raw) {
    throw Object.assign(
      new Error('Playlist not found or expired. Please generate a new one.'),
      { statusCode: 404 },
    )
  }
  const blueprint = JSON.parse(raw) as PlaylistBlueprint

  // Resolve all tracks to platform IDs
  const { resolved, failedCount } = await resolveBlueprint(blueprint, platform, userId)

  if (resolved.length === 0) {
    throw Object.assign(
      new Error('No tracks could be matched on this platform. Try a different platform.'),
      { statusCode: 422 },
    )
  }

  // Harmonic sequencing — Spotify only (§16.5); other platforms fall back to tag-based order
  const orderedTrackIds = await getOrderedTrackIds(resolved, platform, userId)

  // Create the playlist on the platform and add tracks
  const { platformPlaylistId, platformPlaylistUrl } = await createPlatformPlaylist(
    platform,
    orderedTrackIds,
    userId,
  )

  // Persist export result to PlaylistRecord
  await prisma.playlistRecord.update({
    where: { id: blueprintId },
    data: { platformPlaylistId, platformPlaylistUrl, trackCount: resolved.length },
  })

  // Record export signal for ML pipeline
  await prisma.userSignal.create({
    data: {
      userId,
      signalType: 'playlist_created',
      data: { blueprintId, platform, trackCount: resolved.length, failedTracks: failedCount },
    },
  })

  return { platformPlaylistId, platformPlaylistUrl, trackCount: resolved.length, failedTracks: failedCount }
}

// ─── Harmonic sequencing ──────────────────────────────────────────────────────

async function getOrderedTrackIds(
  resolved: ResolvedTrack[],
  platform: string,
  userId: string,
): Promise<string[]> {
  if (platform !== 'spotify') {
    // Other platforms don't expose audio features — use tag-based order as-is
    return resolved.map(r => r.platformTrackId)
  }

  try {
    const accessToken = await getAccessToken(userId, 'spotify')
    const features = await getSpotifyAudioFeatures(
      resolved.map(r => r.platformTrackId),
      accessToken,
    )
    const ordered = harmonicSequence(resolved, features)
    return ordered.map(r => r.platformTrackId)
  } catch {
    // Sequencing failure is non-fatal — fall back to tag-based order
    return resolved.map(r => r.platformTrackId)
  }
}

// ─── Platform dispatch ────────────────────────────────────────────────────────

async function createPlatformPlaylist(
  platform: string,
  trackIds: string[],
  userId: string,
): Promise<{ platformPlaylistId: string; platformPlaylistUrl: string }> {
  if (platform === 'spotify') return createSpotifyExport(trackIds, userId)
  throw Object.assign(new Error(`${platform} export not yet implemented`), { statusCode: 501 })
}

async function createSpotifyExport(
  trackIds: string[],
  userId: string,
): Promise<{ platformPlaylistId: string; platformPlaylistUrl: string }> {
  let accessToken = await getAccessToken(userId, 'spotify')

  const withRefresh = async <T>(fn: (token: string) => Promise<T>): Promise<T> => {
    try {
      return await fn(accessToken)
    } catch (err: unknown) {
      if ((err as { statusCode?: number }).statusCode === 401) {
        accessToken = await refreshSpotifyToken(userId)
        return fn(accessToken)
      }
      throw err
    }
  }

  const spotifyUserId = await withRefresh(t => getSpotifyUserId(t))

  const { id: playlistId, url } = await withRefresh(t =>
    createSpotifyPlaylist('Groovz Mix', 'Generated by Groovz', spotifyUserId, t),
  )

  await withRefresh(t => addTracksToSpotifyPlaylist(playlistId, trackIds, t))

  return { platformPlaylistId: playlistId, platformPlaylistUrl: url }
}
